###
POST http://localhost:80/users HTTP/1.1
Content-Type: application/json

{
    "name": "david44444",
    "username": "david5445",
    "password": "prueba5445"
}

###
GET http://localhost:80/users HTTP/1.1

###
GET http://localhost:80/users/629e33bd1a3bd30014313ad5 HTTP/1.1

###
PUT http://localhost:80/users/629e33bd1a3bd30014313ad5 HTTP/1.1
Content-Type: application/json

{
  "name": "DAVID ROMERO RODILLA PRUEBA",
  "username": "DROMERO99999",
  "password": "contraseña55contraseña55"
}

###
DELETE http://localhost:80/users/629e33bd1a3bd30014313ad5 HTTP/1.1